version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.dockerfile

  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    links:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme-challenge:/tmp/acme-challenge
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro

    ports:
      - 80:80
      - 443:443
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.dockerfile

    # platform: linux/amd64
    volumes:
      - /secrets:/secrets
    environment:
      ASPNETCORE_URLS: http://+:4040
    ports:
      - 4040:4040
  certbot:
    container_name: 'certbot'
    image: certbot/certbot:latest
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email dalton2369@gmail.com --agree-tos --no-eff-email
      -d daltonboggs.dev    entrypoint: ''
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - '/tmp/acme-challenge:/tmp/acme-challenge'
      - ./certbot/data:/var/www/certbot
    environment:
      - TERM=xterm
    depends_on:
      - nginx
