version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.dockerfile

  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    links:
      - backend
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

    ports:
      - 80:80
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.dockerfile

    # platform: linux/amd64
    volumes:
      - /secrets:/secrets
    environment:
      ASPNETCORE_URLS: http://+:4040
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
