services:
  nextjs:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.development.dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    ports:
      - '3000:3000'
    restart: always
    environment:
      - 'NEXT_WEBPACK_USEPOLLING=1'
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    links:
      - backend
    ports:
      - 80:80

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.development.dockerfile

    # platform: linux/amd64
    volumes:
      - c:/secrets:/secrets
    environment:
      ASPNETCORE_URLS: http://+:4040
