version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.dockerfile

  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    links:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme-challenge:/tmp/acme-challenge

    ports:
      - 80:80
      - 443:443
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.dockerfile

    # platform: linux/amd64
    volumes:
      - /secrets:/secrets
    environment:
      ASPNETCORE_URLS: http://+:4040
    expose:
      - 4040:4040
  letsencrypt:
    container_name: "certbot"
    image: certbot/certbot
    command: sh -c "certbot certonly --webroot -w /tmp/acme-challenge/ -d daltonboggs.dev --text --agree-tos --email shanas@mrshanas.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme-challenge:/tmp/acme-challenge"
    environment:
      - TERM=xterm
