services:
  #nextjs:
  #  build:
  #    context: .
  #    dockerfile: ./dockerfiles/frontend.development.dockerfile
  #  volumes:
  #    - ./frontend:/frontend
  #    - /frontend/node_modules
  #    - /frontend/.next
  #  ports:
  #    - '3000:3000'
  #  #environment:
  #  #  - NODE_ENV=development
  #postgres:
  #  container_name: postgres
  #  image: postgres:latest
  #  environment:
  #    - POSTGRES_USER=${POSTGRES_USER}
  #    - POSTGRES_PASSWORD=${POSTGRES_PW}
  #    #- POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
  #  ports:
  #    - '5432:5432'
  #  restart: always
  #  volumes:
  #    - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend.dockerfile
    ports:
      - 5000:5000
    volumes:
      - '/map_backend:/backend'
volumes:
  db-data:
    driver: local
