on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Deploy to VPS
            
              run: |
                      echo $(ls)
                      #git pull origin main
                      #make down
                      #make build
                      #echo "Deleting old image(s)..."
                      #docker image prune -a -f
