name: Deployment
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: ${{ secrets.HOST }} 
        SSHKEY: ${{ secrets.SSH }} 
        NAME: ubuntu-s-1vcpu-1gb-nyc1-01
        PORT: ${{ secrets.PORT }}
        USER: ${{ secrets.USER }}
    - run: ssh production ls --help
