name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: ${{ secrets.HOST }} # example.com || 8.8.8.8
        SSHKEY: ${{ secrets.SSH }} # ----- BEGIN RSA PRIVATE KEY----- ...
        NAME: ubuntu-s-1vcpu-1gb-nyc1-01
        PORT: ${{ secrets.PORT }} # 3000
        USER: ${{ secrets.USER }} # admin
    - run: ssh production ls --help
